server:
  port:8088

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wilterson-franco/tutorias/tree/main/instructor-led/pluralsight/Java-Microservices-with-Spring-Cloud-Developing-Services/config-repo
